name: rewrite-frankframework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.yml"
      - "**.txt"
      - ".github/**"
jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          java: [ '11' ]

      steps:
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-dependencies
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Create Maven settings.xml file
        if: ${{ env.USE_PROPRIETARY == 'true' }}
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "proprietary", "username": "${{ secrets.CI_USER }}", "password": "${{ secrets.CI_PASS }}"}]'

      - name: Update environment when JDK == 11
        if: ${{ matrix.java == '11' }}
        run: |
          echo "MAVEN_GOALS=${{ env.MAVEN_GOALS }} org.sonarsource.scanner.maven:sonar-maven-plugin:sonar" >> $GITHUB_ENV

      - name: Debug - Show Current Directory
        run: pwd

      - name: Debug - List All Files (Recursive)
        run: ls -Rla

      - name: Fix Line Endings
        run: sed -i -e 's/\r$//' mvnw

      - name: Make `mvnw` Executable
        run: chmod +x /home/runner/work/rewrite-frankframework/rewrite-frankframework/mvnw

      - name: Debug - List Files Again
        run: ls -la

      - name: Build with Maven
        env:
          CI_SERVICE: GITHUB
          TZ: Europe/Amsterdam
          JAVA_OPTS: "-Xms1G -XX:+UseParallelGC"
          jdk11: true # allows the use of the JDK11 profile, when running JDK11
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # SonarCloud
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # SonarCloud
        run: ./mvnw -B -T1 ${{env.MAVEN_GOALS}} -Dsonar.projectKey=frankframework_rewrite-frankframework
