name: rewrite-frankframework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.yml"
      - "**.txt"
      - ".github/**"
jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          java: [ '11' ]

      steps:
      - name: Checkout full repository with all branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Make `mvnw` executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean verify

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-dependencies
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Update environment when JDK == 11
        if: ${{ matrix.java == '11' }}
        run: |
          echo "MAVEN_GOALS=${{ env.MAVEN_GOALS }} org.sonarsource.scanner.maven:sonar-maven-plugin:sonar" >> $GITHUB_ENV

      - name: Build with Maven
        env:
          CI_SERVICE: GITHUB
          TZ: Europe/Amsterdam
          JAVA_OPTS: "-Xms1G -XX:+UseParallelGC"
          jdk11: true # allows the use of the JDK11 profile, when running JDK11
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # SonarCloud
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # SonarCloud
        run: mvn -B -T1 ${{env.MAVEN_GOALS}} -Dsonar.projectKey=frankframework_rewrite-frankframework -Dsonar.analysis.mode=publish -Dsonar.branch.name=main
